language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
sudo: false
install:
  - pip install pytest
  - pip install pytest-cov
  - python setup.py install
script:
  - python setup.py test
  - py.test --cov-config .coveragerc --cov=flashtext test/
after_success:
  - coveralls
